language: cpp
cache:
  directories:
env:
  global:
    # Bluespec
    - BLUESPECDIR=$PWD/Bluespec-2015.09.beta2/lib
    - PATH=$PATH:$PWD/Bluespec-2015.09.beta2/bin
    - LD_LIBRARY_PATH=$PWD/lib
    # Riscy
    - RISCY_HOME=$PWD
    - RISCY_TOOLS=$RISCY_HOME/riscv
    - RISCV=$RISCY_TOOLS
    - PATH=$RISCY_TOOLS/bin:$PATH
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$RISCY_TOOLS/lib
  matrix:
    - TRAVIS_PROC=RV64G_multicycle       TRAVIS_TARGET=bluesim
    - TRAVIS_PROC=RV64G_multicycle_split TRAVIS_TARGET=bluesim
    - TRAVIS_PROC=RV32I_multicycle       TRAVIS_TARGET=bluesim
before_script:
  # get all submodules
  - git submodule update --init --recursive
  # build riscv-tools
  - mkdir -p $RISCV
  - export CXX=g++-4.8 CC=gcc-4.8
  - cd tools
  - ./build.sh &> /dev/null
  - cd ..
  # download and install bluespec
  - if [ -d Bluespec-2015.09.beta2 ] ; then echo bluespec cached; else curl http://www.bluespec.com/downloads/Bluespec-2015.09.beta2.tar.gz | tar -zxf - ; fi
  - mkdir -p lib
  - ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 lib/libgmp.so.3
  # download and install ply
  - curl http://www.dabeaz.com/ply/ply-3.9.tar.gz | tar -zxf -
  - ln -s ../ply-3.9/ply scripts
  - ls -l scripts/ply
script:
  - ls Bluespec-2015.09.beta2
  - ls riscv
  - export PYTHONPATH=$PWD/scripts; cd $RISCY_HOME/procs/$TRAVIS_PROC && make build.$TRAVIS_TARGET && make isatest.$TRAVIS_TARGET
sudo: no
dist: trusty
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # riscv-tools
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      # connectal
      - python-dev
      - python-ply
      - libjsoncpp-dev
      # bsc
      - libgmp10
