language: cpp
cache:
  directories:
env:
  global:
    # Bluespec
    - BLUESPECDIR=$PWD/Bluespec-2016.07.beta1/lib
    - PATH=$PATH:$PWD/Bluespec-2016.07.beta1/bin:$PWD/verilator/bin
    - LD_LIBRARY_PATH=$PWD/lib
  matrix:
    - TRAVIS_PROC=RV64G_multicycle  TRAVIS_ISA_SIZE=64
    - TRAVIS_PROC=RV32IM_3stage     TRAVIS_ISA_SIZE=32
before_script:
  # get all submodules
  - git submodule update --init --recursive
  # build riscv-tools
  # - mkdir -p $RISCV
  # - export CXX=g++-4.8 CC=gcc-4.8
  # - cd tools
  # - travis_wait 45 ./build.sh
  # - cd ..
  # download pre-compiled tests
  # download and install bluespec
  - if [ -d Bluespec-2016.07.beta1 ] ; then echo bluespec cached; else curl http://www.bluespec.com/downloads/Bluespec-2016.07.beta1.tar.gz | tar -zxf - ; fi
  - mkdir -p lib
  - ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 lib/libgmp.so.3
  # download and install verilator
  - curl -L http://www.veripool.org/ftp/verilator-3.888.tgz | tar -zxf - ; cd verilator-3.888/ ; ./configure --prefix=`dirname $PWD`/verilator ; make -j3 ; make install ; cd ..
  # download and install ply
  - curl http://www.dabeaz.com/ply/ply-3.9.tar.gz | tar -zxf -
  - ln -s ../ply-3.9/ply connectal/scripts
  - ls -l connectal/scripts/ply
script:
  # download pre-compiled tests
  - cd tools ; curl http://csg.csail.mit.edu/riscy-e/data/RV${TRAVIS_ISA_SIZE}G.tar.gz | tar -zxf - ; cd ..
  - . setup.sh RV${TRAVIS_ISA_SIZE}G
  - cd $RISCY_HOME/procs/$TRAVIS_PROC && make verilator && ./runtest.sh 1 0
sudo: no
dist: trusty
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # riscv-tools
      - gcc-4.8
      - g++-4.8
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      # connectal
      - python-dev
      - python-ply
      - libjsoncpp-dev
      # bsc
      - libgmp10
